[phases.setup]
nixPkgs = [
  "nodejs_22",
  "npm-10_x",
  "openssl",
  "cairo",
  "pango",
  "libjpeg",
  "giflib",
  "librsvg",
  "pixman"
]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]
